# Generated by Django 3.2.16 on 2023-02-04 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredients',
            name='amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='\n                Количество не может быть меньше 1\n                ')], verbose_name='Количество'),
        ),
    ]
