# Generated by Django 3.2.16 on 2023-01-29 09:32

from django.db import migrations, models
import enumchoicefield.fields
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230128_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_favorited',
            field=enumchoicefield.fields.EnumChoiceField(default=recipes.models.Includes(2), enum_class=recipes.models.Includes, max_length=12),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_in_shopping_cart',
            field=enumchoicefield.fields.EnumChoiceField(default=recipes.models.Includes(2), enum_class=recipes.models.Includes, max_length=12),
        ),
        migrations.AddField(
            model_name='recipe',
            name='text',
            field=models.TextField(default='Собираюсь с мыслями..', verbose_name='Описание рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название рецепта'),
        ),
    ]
