# Generated by Django 3.2.16 on 2023-01-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230129_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='measurement_units',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(default='гр.', max_length=200, verbose_name='Единицы измерения'),
        ),
    ]
