# Generated by Django 3.2.16 on 2023-01-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230129_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='quantity',
            new_name='amount',
        ),
    ]
