# Generated by Django 3.2.16 on 2023-01-30 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_rename_quantity_ingredient_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_favorited',
            field=enumchoicefield.fields.EnumChoiceField(default=recipes.models.Includes(2), enum_class=recipes.models.Includes, max_length=12),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_in_shopping_cart',
            field=enumchoicefield.fields.EnumChoiceField(default=recipes.models.Includes(2), enum_class=recipes.models.Includes, max_length=12),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', through='recipes.RecipeIngredients', to='recipes.Ingredient', verbose_name='Список ингредиентов'),
        ),
    ]
