# Generated by Django 3.2.16 on 2023-01-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230128_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
